### ISSUE TITLE
Rationale behind linear backoff

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [express-rate-limit/express-slow-down#21]
Can one explain why linear backoff (additive) is appropriate here? Rather than exponential backoff (multiplicative) for instance.

**Comment by nfriedly** [comment]
Hey, sorry I missed this; notifications got turned off somehow.

As for linear vs exponential, linear seemed to work well enough, so I just left it at that.

**Comment by nfriedly** [comment]
Yeah, that sounds fine. If we made it a function, you'd probably want to pass in a few arguments - the number of hits, the request, the response, maybe the full configuration.

Actually, if we made it trigger after setting req.slowdown instead of before, we could use that for the current number of hits. So, the default might look like

```js
function calculateDelay(req, res, config) {
  return (req.slowdown.current - config.delayAfter) * config.delayMs;
}
```

and then this line could be updated with a call to `config.calculateDelay` instead of doing the math there: https://github.com/express-rate-limit/express-slow-down/blob/c70c381722ae03695ebdde4e112e3f6780fb4070/lib/express-slow-down.js#L65

And then we could offer a built-in exponential option that did `Math.pow()` instead of `*`, or folks could come up with their own.
