### ISSUE TITLE
Incompatible with latest rate-limit-redis RedisStore

### ISSUE THREAD

**Issue by gitChristian** [express-rate-limit/express-slow-down#24]
The exported object RedisStore, of npm module `rate-limit-redis` does not have property `incr`. Even if I change the name from `increment` to `incr` it gives run time error.
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/9953695/167262500-3d3453bf-2b87-4f5f-8039-6c82c9490a62.png">

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/9953695/167262469-13c9a35a-54bc-412e-bde3-f4c956e42b86.png">

**Comment by nfriedly** [comment]
For now, you should go with the older version of rate-limit-redis.

This project should get updated to support the new API, but that is going to be a fairly involved process and won't happen very quickly.

**Comment by ouraios** [comment]
@nfriedly The problem here is that your other package https://github.com/nfriedly/express-rate-limit is compatible with latest version of `rate-limit-redis`  and make it very uncomfortable to use both library in a same project if we want latest version on each of them :/
Maybe i can help to make it usable for both old and new api of store ?

**Comment by nfriedly** [comment]
Well, the latest version express-rate-limit is backwards compatible with the older version of rate-limit-redis, so that shouldn't be an issue. rate-limit-redis is the only one you'll need to pin to an older version for now.

But, yes, if you can update express-slow-down to support the newer API, I would appreciate that.

The roadmap in my mind was to fix up the test reliability first, and then update the API, possibly converting to typescript at the same time as the API update. That's the basic path we took for express-rate-limit.

**Comment by nfriedly** [comment]
Step 1 is done - we now have full test coverage across windows, mac, and linux with multiple versions of node.js tested on each.

I'm toying with the idea of rebuilding express-slow-down on top of express-rate-limit, essentially as just a custom `handler` callback that delays the request instead of responding with an error page. I think it would solve the store compatibility issue once and for all, while at the same time making this repo smaller and simpler.

**Comment by ouraios** [comment]
@nfriedly i couldnt agree more about your idea of rebuilding express-slow-down into express-rate-limit, that would make things way easier to handle with only one package to use by everyone. After all slowing down request usually go with rate limit

**Comment by huksley** [comment]
when this could be solved? it does not work out of the box, maybe there is some glue code someone have?

**Comment by nfriedly** [comment]
Thanks to @AdrianoRuberto v1.6.0 now has support for the newer promise-based Store API that express-rate-limit now uses. It should also retain backwards compatibility with older stores.

Please test it out and let me know if you run into any issues.
