### ISSUE TITLE
onLimitReached , or running custom code

### ISSUE THREAD

**Issue by stephen-willoughby** [express-rate-limit/express-slow-down#45]
### Description

In v1.5.0 we used `onLimitReached` to log and record metrics of our limiting. `onLimitReached` is no more, as its not in [express-rate-limit](https://github.com/express-rate-limit/express-rate-limit), however in express-rate-limit we can use a handler to perform those actions. As described in your [readme.md](https://github.com/express-rate-limit/express-slow-down#options-from-express-rate-limit), `handler` is not supported in slow-down. Is there an alternative way to run custom code, or are there plans to? 

### Why

Logging and metrics

### Alternatives

Giving up on logging and recording these events

**Comment by nfriedly** [comment]
Oof, I'm sorry, I didn't think about that.

Here's a couple of options that are both a little dumb, but might be good enough:

1) Add a custom middleware that runs after `express-slow-down` and checks `req.slowDown`:
    ```js
    app.use(slowDown({
        // ...
    }));
    app.use((req, res, next) => {
        if (request.slowDown.current === request.slowDown.limit + 1) {
            // onLimitReached code here
        }
        next();
    }));
    ```
    The gotcha with this approach is that it now fires _after_ the delay, whereas `onLimitReached` fired _before_ the delay. That might be acceptable for logging purposes, though.

2) Drop `express-slow-down`, and instead use `express-rate-limit` with a custom handler as shown in the docs. However, make the custom handler slow down responses instead of blocking them:
    ```js
    app.use(rateLimit({
        // ...
        max: 1, // previous delayAfter value here
        handler: (request, response, next, options) => {
            if (request.rateLimit.used === request.rateLimit.limit + 1) {
                // onLimitReached code here
            }
            const delay = (request.used - request.limit) * 1000
            const timerId = setTimeout(next, delay)
            response.on('close', () => clearTimeout(timerId))
        },
    })
    ```
    (Basically recreate a simpler version of express-slow-down v2.0.0.)

**Comment by stephen-willoughby** [comment]
thanks, made do with a variation based on 1. Found a bug see https://github.com/express-rate-limit/express-slow-down/issues/46.

**Comment by nfriedly** [comment]
There's not a plan at the moment, but I won't swear it off entirely. 

`onLimitReached` was removed because it led to a lot of confusion and, as I mentioned above, there are ways of achieving a similar result without it.

I considered trying to add an event-based system to replace it, but haven't found something I'm really happy with yet.
